import { Theme } from "../types";

export const themes: Theme[] = [
  {
    name: "Default",
    wrongType: "#ff0000",
    correctType: "#fff",
    untyped: "#666",
    background: "#1a1a1a",
    buttonBackground: "#fff",
    buttonText: "#FFFFFF",
    cursorColor: "#fff",
    textColor: "#fff",
  },
  {
    name: "Classic Contrast",
    wrongType: "#FF6B6B",
    correctType: "#4CAF50",
    untyped: "#757575",
    background: "#000",
    buttonBackground: "#3F51B5",
    buttonText: "#FFFFFF",
    cursorColor: "#FFFFFF",
    textColor: "#90A4AE",
  },
  {
    name: "Galaxy Nebula",
    wrongType: "#E91E63",
    correctType: "#536DFE",
    untyped: "#BDBDBD",
    background: "#212121",
    buttonBackground: "#3D5AFE",
    buttonText: "#FFFFFF",
    cursorColor: "#3D5AFE",
    textColor: "#c3c3c3",
  },
  {
    name: "Sunset Glow",
    wrongType: "#FF5252",
    correctType: "#FFAB40",
    untyped: "#616161",
    background: "#FFE0B2",
    buttonBackground: "#FF6D00",
    buttonText: "#FFFFFF",
    cursorColor: "#FF6D00",
    textColor: "#8b662f",
  },

  {
    name: "Fire & Ice",
    wrongType: "#FF3D00",
    correctType: "#03A9F4",
    untyped: "#b3daec",
    background: "#2d5669",
    buttonBackground: "#FF3D00",
    buttonText: "#FFFFFF",
    cursorColor: "#03A9F4",
    textColor: "#50a7cd",
  },
  {
    name: "Lavender Dream",
    wrongType: "#da5c5c",
    correctType: "#9e2ab3",
    untyped: "#cfb3d3",
    background: "#F3E5F5",
    buttonBackground: "#8E24AA",
    buttonText: "#FFFFFF",
    cursorColor: "#8E24AA",
    textColor: "#7b2162",
  },
  {
    name: "Midnight Blue",
    wrongType: "#D32F2F",
    correctType: "#1976D2",
    untyped: "#90A4AE",
    background: "#263238",
    buttonBackground: "#1565C0",
    buttonText: "#FFFFFF",
    cursorColor: "#1976D2",
    textColor: "#6796ad",
  },
];
